<?php

return [
    'additional_fees' => 'Additional fees changed',
    'additional_fees_units' => 'Type of additional fees changed',
    'commission' => 'Commission changed',
    'additional_charge_per_adult' => 'Additional charge per adult changed',
    'cancellation_policy_file' => 'New cancellation policy file uploaded',
    'cancellation_policy_days' => 'Cancellation policy days changed',
    'cancellation_policy' => 'Cancellation policy changed',
    'cutoff_date' => 'Cutoff date changed',
    'deposit_policy' => 'Deposit policy changed',
    'min_age_to_check_in' => 'Minimum age to checkin changed',
    'rebate' => 'Rebate per room night changed',
    'tax_rate' => 'Tax rate changed',
    'attrition_rate' => 'Attrition rate changed',
    'rooms' => [
        'rooms_offered' => 'Number of rooms available for %s on %s changed',
        'rooms_required' => 'Number of rooms required for %s on %s changed',
        'rate' => 'Room rate for %s on %s changed',
        'date' => 'New room requirement',
        'description' => 'Description changed for %s room',
        'deleted' => '%s room requirement deleted for %s',
    ],
    'questions' => [
        'new' => 'New question group added',
        'group' => 'Question group name changed',
        'questions' => [
            'question' => 'Question changed',
            'new' => 'New question added',
            'deleted' => 'Question deleted',
            'answer' => 'Answer changed',
        ],
        'deleted' => 'Question group deleted',
    ],
    'term_groups' => [
        'new' => 'New terms group added',
        'name' => 'Terms group name changed',
        'terms' => [
            'description' => 'Term changed',
            'title' => 'Term title changed',
            'new' => 'New term added',
            'deleted' => 'Term deleted',
        ],
        'deleted' => 'Terms Group deleted',
    ],
    'meeting_spaces' => [
        'date' => 'Meeting space date changed',
        'start_time' => 'Meeting space start time changed',
        'end_time' => 'Meeting space end time changed',
        'name' => 'Meeting space room name changed',
        'room_type' => 'Meeting space room type changed',
        'layout' => 'Meeting space room layout changed',
        'attendees' => 'Meeting space attendees changed',
        'equipment' => 'Meeting space equipment changed',
        'requests' => 'Meeting space requests changed',
        'new' => 'New meeting space added',
        'description' => 'Meeting space room description changed',
        'conditions' => 'Meeting space room conditions changed',
        'complimentary' => 'Meeting space Complimentary value changed',
        'room_name' => 'Meeting space room name changed',
        'amount' => 'Meeting space room price changed',
        'amount_units' => 'Meeting space room price unit changed',
        'delete' => 'Meeting space for %s date removed'
    ],
    'food_and_beverage' => [
        'date' => 'Food & Beverage date changed',
        'start_time' => 'Food & Beverage start time changed',
        'end_time' => 'Food & Beverage end time changed',
        'name' => 'Food & Beverage room name changed',
        'room_type' => 'Food & Beverage room type changed',
        'layout' => 'Food & Beverage room layout changed',
        'attendees' => 'Food & Beverage attendees changed',
        'meal' => 'Food & Beverage meal type changed',
        'notes' => 'Food & Beverage notes changed',
        'requests' => 'Food & Beverage requests changed',
        'new' => 'New Food & Beverage added',
        'description' => 'Food & Beverage room description changed',
        'conditions' => 'Food & Beverage room conditions changed',
        'complimentary' => 'Food & Beverage Complimentary value changed',
        'room_name' => 'Food & Beverage room name changed',
        'amount' => 'Food & Beverage room price changed',
        'amount_units' => 'Food & Beverage room price unit changed',
        'delete' => 'Food & Beverage for %s date removed'
    ],

];
